### ISSUE TITLE
[Request] I want to change the button text style when the button is clicked.

### ISSUE THREAD

**Issue by zorro901** [AhmedLSayed9/dropdown_button2#14]
Thank you for implementing the `iconOnClick`option. I would like to ask for another one with a similar function.
I want to change the button text style when the button is clicked like the `iconOnClick` option.
For example, the color of the button text is red when the menu is on.

**Comment by AhmedLSayed9** [comment]
I think making option for styling everything when button is clicked would be a bit confusing and could affect performance.
The `iconOnClick` was good option as flipping the arrow shape is familiar. Instead of adding other options, I'll try to add `onClose` Function to detect when menu closed and then you could use 'onTap' with 'onClose' for more Styling.
