### ISSUE TITLE
IndexedStack + 10k items = horrible perfomance

### ISSUE THREAD

**Issue by vasilich6107** [AhmedLSayed9/dropdown_button2#196]
Hi.
The indexed stack from here
https://github.com/AhmedLSayed9/dropdown_button2/blob/master/packages/dropdown_button2/lib/src/dropdown_button2.dart#L693

causes huge performance penalty on rendering.

This code solved the problem

```dart
      innerItemsWidget = Padding(
        //When buttonWidth & dropdownWidth is null, their width will be calculated
        //from the maximum width of menu items or the hint text (width of IndexedStack).
        //We need to add MenuHorizontalPadding so menu width adapts to max items width with padding properly
        padding: EdgeInsets.symmetric(
          horizontal: _buttonStyle?.width == null && _dropdownStyle.width == null
              ? _getMenuHorizontalPadding()
              : 0.0,
        ),
        child: (widget.isDense
            ? items
            : items.map((Widget item) {
                return SizedBox(
                  height: widget.menuItemStyleData.height,
                  child: item,
                );
              }).toList())[_selectedIndex ?? hintIndex ?? 0],
        // IndexedStack(
        //   index: _selectedIndex ?? hintIndex,
        //   alignment: widget.alignment,
        //   children: [],
        //   // children: widget.isDense
        //   //     ? items
        //   //     : items.map((Widget item) {
        //   //         return SizedBox(
        //   //           height: widget.menuItemStyleData.height,
        //   //           child: item,
        //   //         );
        //   //       }).toList(),
        // ),
      );
```

**Comment by AhmedLSayed9** [comment]
IndexedStack is necessary so that when both `buttonWidth` & `dropdownWidth` is null (not used), their width will be calculated from the maximum width of items or hint text within `IndexedStack`.

It's there for a reason and removing it will break lots of things. It's used in Flutter's [dropdown](https://github.com/flutter/flutter/blob/76a938bfa6d140529c35b4b4657d1984d15b9baa/packages/flutter/lib/src/material/dropdown.dart#L1466) too.

10k items within dropdown should be paginated anyway. There's an open issue for pagination feature https://github.com/AhmedLSayed9/dropdown_button2/issues/111

**Comment by AhmedLSayed9** [comment]
I'll see if that's possible and there's no other edge cases.

**Comment by defint** [comment]
Same issue. I have 8 dropdowns with 100 items each. Would be great to fix it somehow.

**Comment by AhmedLSayed9** [comment]
Upgrade to latest version `3.0.0-beta.5`

When both `buttonHeight` & `buttonWidth` are specified, IndexedStack will not be used anymore.
_Note:_ If `isDense` is set to true, you don't have to specify `buttonHeight` as it'll be specified internally.
