### ISSUE TITLE
Clip behavior for dropDown

### ISSUE THREAD

**Issue by AndreiRoze** [AhmedLSayed9/dropdown_button2#21]
If we have rounded corners on dropDown, scrollbar is partically outside of dropDown. Usually we have "clipBehavior" on widgets to control it. Are we have something to fix it for DropdownButtonFormField2?

![Screenshot_20220406-145741__01](https://user-images.githubusercontent.com/53582576/161981675-7d677040-05ae-4067-a644-de7642345c6f.jpg)

**Comment by AhmedLSayed9** [comment]
We can do something like this. But I think it doesn't look good and I don't know if this is against material design guidelines. Can you confirm it?

![image](https://user-images.githubusercontent.com/70890146/162016051-bb3ae626-3f31-45d5-829d-d4e6e6f3ba6f.jpg)

**Comment by AndreiRoze** [comment]
In my opinion, best solution is manually choose behavior for it. If user would like to have scroll outside of dropDown - he will pass nothing, otherwise he will set "clipBehavior" manually. If set behavior manually not possible or hard to implement, in my opinion scroll indicatior inside of dropDown is better, but you are the author so the choice is yours. About which behavior is better - i dont know, apps from Google and another big companies sometimes also have troubles with scroll indicator (you can check it on main page of Gmail app for android 😂). Thanks for the quick response.

**Comment by AhmedLSayed9** [comment]
The problem is letting user choose behavior for it will affect performance as we already added clipBehavior for the menu items, see #3. so, we'll have 2 clipBehaviors one for menu items and one for scrollbar and the second one with if condition :thinking:.

I think the best to do is to add one clipBehavior for all ( menu items, scrollbar and also ripple effect when pressing items that close to the borders ). I'll push the fix, Thanks @AndreiRoze
