### ISSUE TITLE
CustomDropdownButton2 increase the font size

### ISSUE THREAD

**Issue by Genialngash** [AhmedLSayed9/dropdown_button2#22]
How can one increase the font size of the hint String

**Comment by AhmedLSayed9** [comment]
CustomDropdownButton2 is made so that you can do the same idea with your own customization that serves your project, not using it directly from the package.

Anyway, If you want to use it directly from the package, add another pull request with version 1.3.1 as current version is 1.3.0.

Also, update changelog and update ReadMe current version and CustomDropdownButton2 example. Thanks.
