### ISSUE TITLE
Dropdown Menu overlays BottomNavigationBar

### ISSUE THREAD

**Issue by rootd** [AhmedLSayed9/dropdown_button2#34]
Hello,

I'm using  dropdown_button2: ^1.5.2. My dropdown menu is overlaying my BottomNavigationBar like this:
![DropdownButton2](https://user-images.githubusercontent.com/1213925/170486688-55893080-1062-4f9e-a50a-39554da16975.gif)

In comparison the standard behaviour of default flutter DropdownButton:
![DropdownButton](https://user-images.githubusercontent.com/1213925/170486682-1a1ac820-00c2-457c-b969-8ccdc06905b3.gif)

I'm using DropdownButtonFormField2 inside a widget tree like this:
```
Scaffold
  SingleChildScrollView
    Column
      Padding
        DropdownButtonFormField2
```
```
Padding(
	padding: const EdgeInsets.fromLTRB(40, 20, 40, 20),
	child: DropdownButtonFormField2(
	  decoration: InputDecoration(
	    //Add isDense true and zero Padding.
	    //Add Horizontal padding using buttonPadding and Vertical padding by increasing buttonHeight instead of add Padding here so that The whole TextField Button become clickable, and also the dropdown menu open under The whole TextField Button.
	    isDense: true,
	    contentPadding: EdgeInsets.zero,
	    border: OutlineInputBorder(
	      borderRadius: BorderRadius.circular(15),
	    ),
	    //Add more decoration as you want here
	    //Add label If you want but add hint outside the decoration to be aligned in the button perfectly.
	  ),
	  isExpanded: true,
	  value: selectedCountry,
	  icon: Icon(
	    Icons.arrow_drop_down,
	    color: Colors.white,
	  ),
	  iconSize: 30,
	  buttonHeight: 48,
	  buttonPadding:
	      const EdgeInsets.only(left: 20, right: 10),
	  dropdownDecoration: BoxDecoration(
	    borderRadius: BorderRadius.circular(15),
	  ),
	  items: countries.map((CountryItem country) {
	    return DropdownMenuItem<CountryItem>(
	      value: country,
	      child: Row(
		crossAxisAlignment: CrossAxisAlignment.center,
		children: <Widget>[
		  Image.asset(
		    "assets/images/flags/" +
		        country.code +
		        ".png",
		    height: 20,
		    width: 25,
		  ),
		  SizedBox(
		    width: 10,
		  ),
		  Text(country.name),
		],
	      ),
	    );
	  }).toList(),
	  onChanged: (CountryItem? country) {
	    setState(() {
	      selectedCountry = country;
	    });
	  },
	  onSaved: (value) {},
	),
),
```

dropdownOverButton, dropdownFullScreen and offset aren't working either. Any ideas?

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.1.0-0.0.pre.939, on Fedora Linux 36 (Workstation Edition) 5.17.8-300.fc36.x86_64, locale de_DE.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✗] Linux toolchain - develop for Linux desktop
    ✗ clang++ is required for Linux development.
      It is likely available from your distribution (e.g.: apt install clang), or can be downloaded from https://releases.llvm.org/
    ✗ CMake is required for Linux development.
      It is likely available from your distribution (e.g.: apt install cmake), or can be downloaded from https://cmake.org/download/
    ✗ ninja is required for Linux development.
      It is likely available from your distribution (e.g.: apt install ninja-build), or can be downloaded from
      https://github.com/ninja-build/ninja/releases
    ✗ GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install libgtk-3-dev)
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.67.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

! Doctor found issues in 2 categories.
```

**Comment by AhmedLSayed9** [comment]
Hi rootd,

The standard behaviour of default flutter DropdownButton is not to avoid overlaying BottomNavigationBar, but it has by default a bottom padding of 48.0 "If the DropdownButton not the latest thing on the screen's bottom". so, If you try to do something like this:
![photo_2022-05-26_17-30-17](https://user-images.githubusercontent.com/70890146/170522190-6de5fa3d-0225-4024-9b16-77db02772587.jpg)
You'll not be able to open above that Red Container at the bottom with flutter DropdownButton.
So, I think default bottom padding of 48.0 is not a great idea. That's why I've avoided it.

For the BottomNavigationBar, I think the behavior of overlaying it by the DropdownButton is the correct behavior. You could check DropdownButton above BottomNavigationBar of main apps like Youtube. But, If you would like to avoid it anyway. You should use Offset parameter. Start from something like `Offset(0, 120)` and it should work.

**Comment by rootd** [comment]
Hello,

thank you for your quick reply.
As I stated in my previous message, unfortunately offset: Offset(0, 120) doesn't work for me. The menu simply stays in the exact same position as shown in the first GIF. Oddly enough, offsets in X (like Offset(50,0)) seem to work, only the Y component is affected.

**Comment by AhmedLSayed9** [comment]
I understand you. It's a bit tricky as the menu isn't open below DropdownButton "As there's no enough space" so the Offset in Y will start to affect it starting from a higher value. That's Why I said start from something like 100-150 for Y Offest. and It should work. But, In this case the menu height shouldn't be dynamic to achieve the same position in each time.

**Comment by rootd** [comment]
Indeed using a higher Y offset works, thank you so much for your help :-)
