### ISSUE TITLE
Extra dropdown padding

### ISSUE THREAD

**Issue by olegys** [AhmedLSayed9/dropdown_button2#59]
Bug in version 1.7.1 
In version 1.6.3 it is okey

![Simulator Screen Shot - iPhone 13 Pro Max - 2022-08-01 at 17 02 24](https://user-images.githubusercontent.com/18525409/182166179-e2504aee-683a-471c-8822-bef25c57835e.png)
![Simulator Screen Shot - iPhone 13 Pro Max - 2022-08-01 at 17 03 16](https://user-images.githubusercontent.com/18525409/182166189-a149b0fe-751f-4884-98c0-280e99ad6b9f.png)

**Comment by AhmedLSayed9** [comment]
Can you share a sample code please?

**Comment by olegys** [comment]
> Can you share a sample code please?

DropdownButtonHideUnderline(
      child: DropdownButtonFormField2<T>(
        onMenuStateChange: _menuStateChange,
        value: widget.value,
        itemHeight: 40.0,
        offset: const Offset(0.0, -3.0),
        items: _addDividersAfterItems(),
        customItemsIndexes: _getDividersIndexes(),
        customItemsHeight: 2,
        onChanged: widget.onChanged,
        dropdownDecoration: const BoxDecoration(
          color: AppColors.white,
        ),
        decoration: InputDecoration(
          isCollapsed: true,
          fillColor: AppColors.white,
          filled: true,
          contentPadding: const EdgeInsets.symmetric(
            vertical: 9.0,
          ).copyWith(
            right: 10.0,
          ),
          prefixIconConstraints: const BoxConstraints(
            maxWidth: 33.0,
            maxHeight: 18.0,
          ),
          prefixIcon: Padding(
            padding: const EdgeInsets.only(
              right: 5.0,
              left: 10.0,
            ),
            child: SvgPicture.asset(
              Assets.svg.globe.path,
              alignment: Alignment.centerRight,
            ),
          ),
          border: InputBorder.none,
        ),
        icon: Padding(
          padding: const EdgeInsets.only(
            left: 5.0,
          ),
          child: RotationTransition(
            turns: _rotateAnimation,
            child: SvgPicture.asset(
              Assets.svg.up.path,
              width: 12.0,
            ),
          ),
        ),
      ),
    );

**Comment by AhmedLSayed9** [comment]
That was necessary update to fix #56 and I don't find any other approach to fix it without affecting that you can't use `padding` and `prefixIcon` inside decoration parameter.

But, you can achieve it as explained at the examples, so:
1. Use `isDense: true` and `contentPadding: EdgeInsets.zero` inside decoration and instead (to add padding) add Horizontal padding using `buttonPadding` parameter and Vertical padding by increasing `buttonHeight`. That is necessary so that the whole TextField Button become clickable, and also the dropdown menu open under the whole TextField Button.
2. Don't add prefix icon inside decoration. Instead, as explained at example (2. DropdownButton2 with some styling and customization) add the icon to the `hint` parameter. Also, do the same using `selectedItemBuilder` if you want the icon to still appear when you select an item.
3. 
Hope that helps.
