### ISSUE TITLE
When there is no default value, the first item will be selected. Is there a way to not display this effect?

### ISSUE THREAD

**Issue by yh4922** [AhmedLSayed9/dropdown_button2#6]
![](https://s3.bmp.ovh/imgs/2022/01/3838a2a1595a8136.png)

**Comment by AhmedLSayed9** [comment]
Hi @yh4922 ,
When there is no default value, there shouldn't be any items selected as showing in the example samples.
Can you share a sample code when this issue happen?

**Comment by yh4922** [comment]
> Hi @yh4922 , When there is no default value, there shouldn't be any items selected as showing in the example samples. Can you share a sample code when this issue happen?

This is the example project of this library, I have not done any task modification

**Comment by AhmedLSayed9** [comment]
Well, Selected Item is only highlighted on web and desktop, when `[FocusManager.highlightMode]` is `[FocusHighlightMode.traditional]` that's why I couldn't see this behavior. 
and in that case, First item is considered as the selected index to handle menu animation, position, etc.. "That's Flutter Dropdownbutton behavior".

All we need is to exclude first item to be highlighted when there's no default value.
Also, I noticed the button's color gets highlighted on web and desktop if `buttonDecoration` is set. I'll work to fix that too.
