### ISSUE TITLE
Configurable auto scroll

### ISSUE THREAD

**Issue by muzzah** [AhmedLSayed9/dropdown_button2#60]
Hi

Thanks for the library. Is it possible to turn off the auto scroll feature when the drop down is opened? I dont want the list to auto scroll to the selected Item. 

Thanks

**Comment by AhmedLSayed9** [comment]
I think you can achieve that by manually defining the selected item and also manually updating the hint to show the selected item. In that case, you need to always pass null to `value` parameter "We don't specify any selected item". Refer to example (4. DropdownButton2 as Multiselect Dropdown with Checkboxes) it has the same idea of manually updating the selected item but you'll use value of null and use `hint` instead of `selectedItemBuilder`. Hope that helps.
